### ISSUE TITLE
Proposed v0.29.0 "circle" release: faster AVIF encoding, drop Node.js 10 support

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#2748]
Updates to the prebuilt binaries include:

* [x] Upgrade to forthcoming libvips v8.11.3 for improved multi-threaded performance on Windows (up to ~15%)
* [x] Patch libheif for ~2x faster AVIF encoding
* [x] Reduced binary size, ~12% smaller

Potentially breaking changes:

* [x] AVIF encoding will default to 4:4:4 (i.e. without) chroma subsampling - https://github.com/lovell/sharp/issues/2562
* [x] Upgrade to Node-API (N-API) version 5
* [x] Drop support for Node.js 10, minimum Node.js version will be 12.13.0 (LTS)
* [x] `extractChannel` will default to single-channel (rather than sRGB) - https://github.com/lovell/sharp/issues/2658

Other possible improvements:

* [x] Install prebuilt libvips binaries into `platform-arch` subdirectories under `vendor/x.y.z/` - https://github.com/lovell/sharp/issues/2575
* [x] Expose `heif` compression e.g. AV1, HEVC in metadata output - https://github.com/lovell/sharp/issues/2504
* [x] Optional wider-gamut processing - https://github.com/lovell/sharp/pull/2704
* [x] Always use Brotli-compressed tarballs for prebuilt libvips binaries

**Comment by lovell** [comment]
https://packagephobia.com/result?p=sharp suggests the install size for the latest version is less than 20MB :tada:
