### ISSUE TITLE
Install sharp without downloading binary or building from source

### ISSUE THREAD

**Issue by michielswaanen** [lovell/sharp#3920]
Hi @lovell,

I'm working with a custom-built global libvips and I'm wondering if there's a method to install sharp that neither involves downloading a pre-built binary nor building from source.

Currently, I'm facing an issue where sharp automatically downloads a binary if I don't opt for building from source. This requires me to manually delete the `node_modules/sharp/vendor` directory every time.

Thanks for your assistance,
Michiel

**Comment by lovell** [comment]
The mention of the `vendor` directory suggests you are not using the latest version. Please upgrade and read https://sharp.pixelplumbing.com/install#building-from-source for the latest information about building from source.

**Comment by michielswaanen** [comment]
Correct, I'm on version `0.32.x`, upgraded to `0.33.1`. This doesn't generate a vendor folder anymore. 

However my globally installed libvips isn't used now, will search for this one myself.

Thanks for the quick helps!

**Comment by michielswaanen** [comment]
Hey @lovell I'd like to seek some extra clarification on the installation process for sharp. Specifically, is it necessary to build sharp from source if I already have vips installed globally and it's functioning correctly via the CLI?

**Comment by lovell** [comment]
If you are using any custom or globally-install libvips then you have to build sharp from source against that specific version.

**Comment by michielswaanen** [comment]
Hi @lovell 

I tried building it but I'm encountering challenges while attempting to build sharp on Alpine Linux. Despite following the documentation, the build process fails with the error message: Error: 'make' failed with exit code: 2.

Based on the documentation, it seems like the build should proceed without issues. 

I've filled in the template for extra information.

---



## Possible install-time or require-time problem



- [x] I have read and understood all of the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [x] I have searched for known bugs relating to this problem in my choice of package manager.

You must confirm both of these before continuing.

### Are you using the latest version of sharp?



- [x] I am using the latest version of `sharp` as reported by `npm view sharp dist-tags.latest`.

If you cannot confirm this, please upgrade to the latest version and try again before opening an issue.

If you are using another package which depends on a version of `sharp` that is not the latest,
please open an issue against that package instead.

### Are you using a supported runtime?



- [x] I am using Node.js with a version that satisfies `^18.17.0 || ^20.3.0 || >=21.0.0`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these,
please upgrade to the latest version
and try again before opening an issue.

### Are you using a supported package manager and installing optional dependencies?



- [ ] I am using npm >= 9.6.5 with `--include=optional`
- [ ] I am using yarn >= 3.2.0
- [x] I am using pnpm >= 7.1.0 with `--no-optional=false`
- [ ] I am using Deno
- [ ] I am using Bun

If you cannot confirm any of these, please upgrade to the latest version of your chosen package manager
and ensure you are allowing the installation of optional or multi-platform dependencies before opening an issue.

### What is the complete error message, including the full stack trace?

```
.../sharp@0.33.1/node_modules/sharp install$ node install/check
.../sharp@0.33.1/node_modules/sharp install: sharp: Detected globally-installed libvips v8.15.1
.../sharp@0.33.1/node_modules/sharp install: sharp: Attempting to build from source via node-gyp
.../sharp@0.33.1/node_modules/sharp install: sharp: Found node-addon-api
.../sharp@0.33.1/node_modules/sharp install: sharp: Found node-gyp version 10.0.1
.../sharp@0.33.1/node_modules/sharp install: sharp: See https://sharp.pixelplumbing.com/install#building-from-source
.../sharp@0.33.1/node_modules/sharp install: gyp info it worked if it ends with ok
.../sharp@0.33.1/node_modules/sharp install: gyp info using node-gyp@9.4.1
.../sharp@0.33.1/node_modules/sharp install: gyp info using node@21.5.0 | linux | x64
.../sharp@0.33.1/node_modules/sharp install: gyp info chdir src
.../sharp@0.33.1/node_modules/sharp install: gyp info find Python using Python version 3.11.6 found at "/usr/bin/python3"
.../sharp@0.33.1/node_modules/sharp install: gyp http GET https://unofficial-builds.nodejs.org/download/release/v21.5.0/node-v21.5.0-headers.tar.gz
.../sharp@0.33.1/node_modules/sharp install: gyp http 200 https://unofficial-builds.nodejs.org/download/release/v21.5.0/node-v21.5.0-headers.tar.gz
.../sharp@0.33.1/node_modules/sharp install: gyp http GET https://unofficial-builds.nodejs.org/download/release/v21.5.0/SHASUMS256.txt
.../sharp@0.33.1/node_modules/sharp install: gyp http 200 https://unofficial-builds.nodejs.org/download/release/v21.5.0/SHASUMS256.txt
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn /usr/bin/python3
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args [
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   'binding.gyp',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-f',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   'make',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-I',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '/app/node_modules/.pnpm/sharp@0.33.1/node_modules/sharp/src/build/config.gypi',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-I',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-I',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '/root/.cache/node-gyp/21.5.0/include/node/common.gypi',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-Dlibrary=shared_library',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-Dvisibility=default',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/21.5.0',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/21.5.0/<(target_arch)/node.lib',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/.pnpm/sharp@0.33.1/node_modules/sharp/src',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-Dnode_engine=v8',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '--depth=.',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '--no-parallel',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '--generator-output',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   'build',
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args   '-Goutput_dir=.'
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args ]
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn make
.../sharp@0.33.1/node_modules/sharp install: gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
.../sharp@0.33.1/node_modules/sharp install: make: Entering directory '/app/node_modules/.pnpm/sharp@0.33.1/node_modules/sharp/src/build'
.../sharp@0.33.1/node_modules/sharp install:   CC(target) Release/obj.target/nothing/../../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.o
.../sharp@0.33.1/node_modules/sharp install: rm -f Release/obj.target/../../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a Release/obj.target/../../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/../../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a`
.../sharp@0.33.1/node_modules/sharp install: ar crs Release/obj.target/../../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a @Release/obj.target/../../../../node-addon-api@5.1.0/node_modules/node-addon-api/nothing.a.ar-file-list
.../sharp@0.33.1/node_modules/sharp install:   COPY Release/nothing.a
.../sharp@0.33.1/node_modules/sharp install:   TOUCH Release/obj.target/libvips-cpp.stamp
.../sharp@0.33.1/node_modules/sharp install:   CXX(target) Release/obj.target/sharp-linuxmusl-x64/common.o
.../sharp@0.33.1/node_modules/sharp install:   CXX(target) Release/obj.target/sharp-linuxmusl-x64/metadata.o
.../sharp@0.33.1/node_modules/sharp install: ../metadata.cc: In member function 'virtual void MetadataWorker::OnOK()':
.../sharp@0.33.1/node_modules/sharp install: ../metadata.cc:233:46: error: 'NewOrCopy' is not a member of 'Napi::Buffer<char>'
.../sharp@0.33.1/node_modules/sharp install:   233 |         info.Set("exif", Napi::Buffer<char>::NewOrCopy(env, baton->exif, baton->exifLength, sharp::FreeCallback));
.../sharp@0.33.1/node_modules/sharp install:       |                                              ^~~~~~~~~
.../sharp@0.33.1/node_modules/sharp install: ../metadata.cc:236:45: error: 'NewOrCopy' is not a member of 'Napi::Buffer<char>'
.../sharp@0.33.1/node_modules/sharp install:   236 |         info.Set("icc", Napi::Buffer<char>::NewOrCopy(env, baton->icc, baton->iccLength, sharp::FreeCallback));
.../sharp@0.33.1/node_modules/sharp install:       |                                             ^~~~~~~~~
.../sharp@0.33.1/node_modules/sharp install: ../metadata.cc:239:46: error: 'NewOrCopy' is not a member of 'Napi::Buffer<char>'
.../sharp@0.33.1/node_modules/sharp install:   239 |         info.Set("iptc", Napi::Buffer<char>::NewOrCopy(env, baton->iptc, baton->iptcLength, sharp::FreeCallback));
.../sharp@0.33.1/node_modules/sharp install:       |                                              ^~~~~~~~~
.../sharp@0.33.1/node_modules/sharp install: ../metadata.cc:242:45: error: 'NewOrCopy' is not a member of 'Napi::Buffer<char>'
.../sharp@0.33.1/node_modules/sharp install:   242 |         info.Set("xmp", Napi::Buffer<char>::NewOrCopy(env, baton->xmp, baton->xmpLength, sharp::FreeCallback));
.../sharp@0.33.1/node_modules/sharp install:       |                                             ^~~~~~~~~
.../sharp@0.33.1/node_modules/sharp install: ../metadata.cc:246:31: error: 'NewOrCopy' is not a member of 'Napi::Buffer<char>'
.../sharp@0.33.1/node_modules/sharp install:   246 |           Napi::Buffer<char>::NewOrCopy(env, baton->tifftagPhotoshop,
.../sharp@0.33.1/node_modules/sharp install:       |                               ^~~~~~~~~
.../sharp@0.33.1/node_modules/sharp install: make: *** [sharp-linuxmusl-x64.target.mk:173: Release/obj.target/sharp-linuxmusl-x64/metadata.o] Error 1
.../sharp@0.33.1/node_modules/sharp install: make: Leaving directory '/app/node_modules/.pnpm/sharp@0.33.1/node_modules/sharp/src/build'
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! build error 
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! stack Error: `make` failed with exit code: 2
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/build.js:203:23)
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--directory=src"
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! cwd /app/node_modules/.pnpm/sharp@0.33.1/node_modules/sharp/src
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! node -v v21.5.0
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! node-gyp -v v9.4.1
.../sharp@0.33.1/node_modules/sharp install: gyp ERR! not ok 
.../sharp@0.33.1/node_modules/sharp install: Failed
```

### What is the complete output of running `npm install --verbose --foreground-scripts sharp` in an empty directory?

<details>

```
/app # npm install --verbose --foreground-scripts sharp
npm verb cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@10.2.4
npm info using node@v21.5.0
npm verb title npm install sharp
npm verb argv "install" "--loglevel" "verbose" "--foreground-scripts" "sharp"
npm verb logfile logs-max:10 dir:/root/.npm/_logs/2023-12-28T15_16_22_543Z-
npm verb logfile /root/.npm/_logs/2023-12-28T15_16_22_543Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/sharp 267ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/color 98ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 237ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 243ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-x64 289ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-darwin-arm64 292ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-x64 316ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-s390x 317ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-arm64 320ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-s390x 325ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-wasm32 328ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linuxmusl-x64 329ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-x64 348ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-arm64 354ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-x64 355ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-ia32 355ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm 357ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linuxmusl-arm64 359ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-linux-arm64 394ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-win32-x64 422ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm 447ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-darwin-x64 467ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@img%2fsharp-libvips-linux-arm64 691ms (cache miss)
npm verb stack TypeError: Cannot read properties of null (reading 'matches')
npm verb stack     at Link.matches (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1115:41)
npm verb stack     at Link.canDedupe (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1069:15)
npm verb stack     at PlaceDep.pruneDedupable (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:426:14)
npm verb stack     at new PlaceDep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:278:14)
npm verb stack     at #buildDepStep (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:933:18)
npm verb stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)      
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
npm verb stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:152:5)
npm verb stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli-entry.js:61:5)
npm verb cwd /app
npm verb Linux 5.15.90.1-microsoft-standard-WSL2
npm verb node v21.5.0
npm verb npm  v10.2.4
npm ERR! Cannot read properties of null (reading 'matches')
npm verb exit 1
npm verb unfinished npm timer reify 1703776582818
npm verb unfinished npm timer reify:loadTrees 1703776582827
npm verb unfinished npm timer idealTree:buildDeps 1703776586756
npm verb unfinished npm timer idealTree:node_modules/sharp 1703776587743
npm verb code 1

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-12-28T15_16_22_543Z-debug-0.log
```

</details>

### What is the output of running `npx envinfo --binaries --system --npmPackages=sharp --npmGlobalPackages=sharp`?

```
  System:
    OS: Linux 5.15 Alpine Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.96 GB / 15.58 GB
    Container: Yes
    Shell: 1.36.1 - /bin/ash
  Binaries:
    Node: 21.5.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.13.1 - /usr/local/bin/pnpm
```

### Dockerfile
```Dockerfile
##################################
#                                #
#       Alpine with nodejs       #
#                                #
##################################

FROM node:21-alpine3.18 AS node

##################################
#                                #
#   Alpine with custom libvips   #
#                                #
##################################

FROM ghcr.io/clipido/clipido-2/alpine3.18-libvips8.15.1 as base

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN npm install -g pnpm turbo wait-on

##################################
#                                #
#   Stage 1: Scaffold monorepo   #
#       Usage: prod & dev        #
#                                #
##################################

FROM base as pruner

WORKDIR /app

COPY . .

RUN turbo prune --scope=@apps/api --out-dir=pruned --docker && \
    apk update && \
    apk add --update python3 make g++

# ... pnpm install happens in a `Tiltfile` for development purposes ...
```

### pkg-config print

`8.15.1`

**Comment by lovell** [comment]
> node-addon-api@5.1.0

Please upgrade `node-addon-api` to the latest version 7.0.0.

**Comment by lovell** [comment]
I've added this to the docs via commit https://github.com/lovell/sharp/commit/0499f59e710f8338779f7a29fec277a7b31da98f

**Comment by lovell** [comment]
@michielswaanen Were you able to make any progress with this?

**Comment by michielswaanen** [comment]
@lovell A package upgrade for `node-addon-api` to version 7+ did the trick. Thanks for the help!
