### ISSUE TITLE
Progress towards sharp v0.34.0

### ISSUE THREAD

**Issue by lovell** [lovell/sharp#4248]
Done so far:

- [X] Upgrade to libvips v8.16.1
- [X] Expose `isPalette` metadata - see https://github.com/libvips/libvips/pull/3756
- [X] Expose WebP `smartDeblock` output option - see https://github.com/libvips/libvips/pull/3852
- [X] Expose recent libjxl features such as animation, EXIF metadata (requires global libvips compiled with support for libjxl)
- [X] Add linux-ppc64le to supported platforms
- [X] Upgrade to C++17 - see https://github.com/lovell/sharp/issues/3943
- [X] Change format of `metadata.background` for greyscale images - see https://github.com/lovell/sharp/issues/4090
- [X] Upgrade to libheif v1.19.1 for AOM auto-tiles feature - see https://github.com/strukturag/libheif/pull/1330
- [X] Merge autoOrient improvements - see https://github.com/lovell/sharp/pull/4151
- [X] Switch docs to Astro Starlight - see eeac8d4
- [X] Expose `vips_arrayjoin` - see https://github.com/lovell/sharp/issues/1580 
- [X] Leak testing
- [X] Performance testing
- [X] Merge erode/dilate feature - see https://github.com/lovell/sharp/pull/4243

**Comment by adityapatadia** [comment]
How safe is it to upgrade libheif to 1.19 to take advantage of the AVIF tiling even when this new version is not released?

**Comment by lovell** [comment]
The first prerelease of v0.34.0 is now available for testing.
```sh
npm install sharp@0.34.0-rc.0
```
Known issues that require further investigation:

- Does not work with Yarn Plug'n'Play
